name: strategy_15
exchange: bybit
trading_pairs_file: data/cycles/bybit_cycles_15.csv
min_profit_bps: 11
max_slippage_bps: 9
max_leg_latency_ms: 379
capital_allocation:
  mode: fixed_fraction
  fraction: 0.6
risk_controls:
  max_open_cycles: 2
  stop_after_consecutive_losses: 3
fees:
  taker_bps: 12
  maker_bps: 4
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 10
  latency_ms: 142
logging:
  level: INFO
  trade_csv: logs/trades_strategy_15.csv
