name: strategy_working
exchange: coinbase
trading_pairs_file: data/cycles/coinbase_cycles_complete.csv

# PROVEN PROFITABLE SETTINGS (based on your successful strategy_1.yaml)
min_profit_bps: 10       # Lower threshold to allow more trades
max_slippage_bps: 200    # Very high slippage tolerance to prevent failures
max_leg_latency_ms: 30000

# Aggressive capital allocation (your original successful setting)
capital_allocation:
  mode: fixed_fraction
  fraction: 0.5

# Relaxed risk controls to allow completion
risk_controls:
  max_open_cycles: 20    # More concurrent trades
  stop_after_consecutive_losses: 10  # More forgiving
  slippage_cooldown_seconds: 5   # Short cooldown
  enable_latency_checks: false   # Disable to prevent failures
  enable_slippage_checks: false  # Disable to prevent failures

# Realistic fees
fees:
  taker_bps: 9
  maker_bps: 4

# Simple order config
order:
  type: market
  allow_partial_fills: true
  min_partial_fill_percentage: 0.95
  max_retries: 3
  retry_delay_ms: 100

# Paper trading with realistic settings
execution:
  mode: paper
  paper:
    fee_bps: 9
    fill_ratio: 0.98
    initial_balances:
      USD: 10000
    random_seed: 42

# Enable simulation (was in your working config)
simulation:
  enable: true
  book_depth_levels: 5
  latency_ms: 139
