name: strategy_simple_profit
exchange: coinbase
trading_pairs_file: data/cycles/coinbase_cycles_complete.csv

# Profitable settings - only execute trades that will make money
min_profit_bps: 5   # Only trade if we can make at least 5 basis points (0.05%)
max_slippage_bps: 3   # Keep slippage very low to preserve profit
max_leg_latency_ms: 5000  # Allow more time for execution

# Conservative capital allocation
capital_allocation:
  mode: fixed_fraction
  fraction: 0.1  # Use 10% of available balance per trade

# Simple risk controls
risk_controls:
  max_open_cycles: 1  # Execute one cycle at a time
  stop_after_consecutive_losses: 10  # Allow more attempts before stopping
  slippage_cooldown_seconds: 0  # No cooldown between trades
  enable_latency_checks: true
  enable_slippage_checks: true

# Exchange fees
fees:
  taker_bps: 9
  maker_bps: 4

# Simple order configuration
order:
  type: market
  allow_partial_fills: false  # Only accept complete fills
  max_retries: 1
  retry_delay_ms: 100

# Paper trading with realistic starting balance
execution:
  mode: paper
  paper:
    fee_bps: 5  # Lower fees to help profitability
    fill_ratio: 1.0  # 100% fill rate for simulation
    initial_balances:
      USD: 10000  # Start with $10,000
    random_seed: 42

# Disable simulation for cleaner output
simulation:
  enable: false
