name: strategy_37
exchange: coinbase
trading_pairs_file: data/cycles/coinbase_cycles_7.csv
min_profit_bps: 14
max_slippage_bps: 3
max_leg_latency_ms: 247
capital_allocation:
  mode: fixed_fraction
  fraction: 0.5
risk_controls:
  max_open_cycles: 2
  stop_after_consecutive_losses: 3
fees:
  taker_bps: 8
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 9
  latency_ms: 130
logging:
  level: INFO
  trade_csv: logs/trades_strategy_37.csv
