name: strategy_7
exchange: coinbase
trading_pairs_file: data/cycles/coinbase_cycles_7.csv
min_profit_bps: 10
max_slippage_bps: 3
max_leg_latency_ms: 155
capital_allocation:
  mode: fixed_fraction
  fraction: 0.6
risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 4
fees:
  taker_bps: 5
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 7
  latency_ms: 135
logging:
  level: INFO
  trade_csv: logs/trades_strategy_7.csv
