name: strategy_25
exchange: bybit
trading_pairs_file: data/cycles/bybit_cycles_25.csv
min_profit_bps: 8
max_slippage_bps: 8
max_leg_latency_ms: 281
capital_allocation:
  mode: fixed_fraction
  fraction: 0.5
risk_controls:
  max_open_cycles: 1
  stop_after_consecutive_losses: 6
fees:
  taker_bps: 12
  maker_bps: 3
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 10
  latency_ms: 114
logging:
  level: INFO
  trade_csv: logs/trades_strategy_25.csv
