name: strategy_22
exchange: coinbase
trading_pairs_file: data/cycles/coinbase_cycles_22.csv
min_profit_bps: 9
max_slippage_bps: 9
max_leg_latency_ms: 187
capital_allocation:
  mode: fixed_fraction
  fraction: 0.6
risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 4
fees:
  taker_bps: 5
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 10
  latency_ms: 94
logging:
  level: INFO
  trade_csv: logs/trades_strategy_22.csv
