name: strategy_9
exchange: okx
trading_pairs_file: data/cycles/okx_cycles_9.csv
min_profit_bps: 16
max_slippage_bps: 7
max_leg_latency_ms: 220
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 1
  stop_after_consecutive_losses: 3
fees:
  taker_bps: 8
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 8
  latency_ms: 79
logging:
  level: INFO
  trade_csv: logs/trades_strategy_9.csv
