name: strategy_39
exchange: okx
trading_pairs_file: data/cycles/okx_cycles_9.csv
min_profit_bps: 7
max_slippage_bps: 6
max_leg_latency_ms: 294
capital_allocation:
  mode: fixed_fraction
  fraction: 0.6
risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 5
fees:
  taker_bps: 12
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 7
  latency_ms: 106
logging:
  level: INFO
  trade_csv: logs/trades_strategy_39.csv
