name: strategy_11
exchange: binance
trading_pairs_file: data/cycles/binance_cycles_11.csv
min_profit_bps: 13
max_slippage_bps: 10
max_leg_latency_ms: 267
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 1
  stop_after_consecutive_losses: 6
fees:
  taker_bps: 12
  maker_bps: 4
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 6
  latency_ms: 55
logging:
  level: INFO
  trade_csv: logs/trades_strategy_11.csv
