name: strategy_35
exchange: bybit
trading_pairs_file: data/cycles/bybit_cycles_5.csv
min_profit_bps: 8
max_slippage_bps: 7
max_leg_latency_ms: 200
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 4
fees:
  taker_bps: 5
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 8
  latency_ms: 86
logging:
  level: INFO
  trade_csv: logs/trades_strategy_35.csv
