name: strategy_28
exchange: kraken
trading_pairs_file: data/cycles/kraken_cycles_28.csv
min_profit_bps: 6
max_slippage_bps: 7
max_leg_latency_ms: 393
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 2
  stop_after_consecutive_losses: 3
fees:
  taker_bps: 12
  maker_bps: 4
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 7
  latency_ms: 134
logging:
  level: INFO
  trade_csv: logs/trades_strategy_28.csv
