name: strategy_18
exchange: kraken
trading_pairs_file: data/cycles/kraken_cycles_18.csv
min_profit_bps: 11
max_slippage_bps: 10
max_leg_latency_ms: 325
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 2
  stop_after_consecutive_losses: 3
fees:
  taker_bps: 5
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 7
  latency_ms: 106
logging:
  level: INFO
  trade_csv: logs/trades_strategy_18.csv
