name: strategy_36
exchange: binance
trading_pairs_file: data/cycles/binance_cycles_6.csv
min_profit_bps: 7
max_slippage_bps: 5
max_leg_latency_ms: 349
capital_allocation:
  mode: fixed_fraction
  fraction: 0.5
risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 5
fees:
  taker_bps: 11
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 10
  latency_ms: 74
logging:
  level: INFO
  trade_csv: logs/trades_strategy_36.csv
