name: strategy_31
exchange: binance
trading_pairs_file: data/cycles/binance_cycles_1.csv
min_profit_bps: 10
max_slippage_bps: 8
max_leg_latency_ms: 338
capital_allocation:
  mode: fixed_fraction
  fraction: 0.5
risk_controls:
  max_open_cycles: 2
  stop_after_consecutive_losses: 3
fees:
  taker_bps: 5
  maker_bps: 4
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 10
  latency_ms: 66
logging:
  level: INFO
  trade_csv: logs/trades_strategy_31.csv
