name: strategy_29
exchange: okx
trading_pairs_file: data/cycles/okx_cycles_29.csv
min_profit_bps: 17
max_slippage_bps: 5
max_leg_latency_ms: 291
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 4
fees:
  taker_bps: 9
  maker_bps: 4
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 6
  latency_ms: 122
logging:
  level: INFO
  trade_csv: logs/trades_strategy_29.csv
