name: strategy_10
exchange: bybit
trading_pairs_file: data/cycles/bybit_cycles_10.csv
min_profit_bps: 14
max_slippage_bps: 4
max_leg_latency_ms: 369
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 4
fees:
  taker_bps: 6
  maker_bps: 4
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 10
  latency_ms: 67
logging:
  level: INFO
  trade_csv: logs/trades_strategy_10.csv
