# Enhanced Strategy Configuration with Multi-Mode Execution Support
name: strategy_robust_example
exchange: kraken
trading_pairs_file: data/cycles/kraken_cycles_8.csv
min_profit_bps: 12
max_slippage_bps: 8
max_leg_latency_ms: 396

# ===== EXECUTION MODE CONFIGURATION =====
execution:
  mode: live  # Options: live, paper, backtest

  # Paper Trading Configuration
  paper:
    fee_bps: 30                    # Fee in basis points
    fill_ratio: 0.95               # Probability of full fill (0.0-1.0)
    spread_padding_bps: 5          # Additional spread padding
    random_seed: 42                # For deterministic testing
    latency_sim_ms: 50             # Simulated latency

    # Initial balances for paper trading
    initial_balances:
      BTC: 1.0
      ETH: 10.0
      USDT: 10000.0
      USDC: 10000.0
      SOL: 100.0

    # Advanced slippage model
    slippage_model:
      base_slippage_bps: 2         # Base slippage
      volatility_multiplier: 1.5   # Volatility impact multiplier
      random_component_bps: 3      # Random slippage component
      adverse_selection_bps: 1     # Adverse selection cost

    # Market impact model for large orders
    market_impact:
      enabled: true
      impact_coefficient: 0.1      # bps per $1000 notional
      max_impact_bps: 50          # Maximum market impact

    # Partial fill simulation
    partial_fill_model:
      enabled: true
      min_fill_ratio: 0.3         # Minimum fill percentage
      fill_time_spread_ms: 500    # Time spread for partial fills
      large_order_threshold: 1000  # USD threshold for partials

  # Backtesting Configuration
  backtest:
    data_file: data/backtests/sample_feed.csv
    start_time: null              # Unix timestamp or null for all data
    end_time: null                # Unix timestamp or null for all data
    time_acceleration: 1.0        # Speed multiplier for simulation
    random_seed: 12345           # Deterministic seed

    # Initial balances for backtesting
    initial_balances:
      BTC: 1.0
      ETH: 5.0
      USDT: 50000.0
      USDC: 50000.0

    # Backtest-specific slippage model
    slippage_model:
      base_slippage_bps: 3
      size_impact_coefficient: 0.05
      max_slippage_bps: 100
      random_component_bps: 2

    # Fill behavior in backtest
    fill_model:
      fill_probability: 0.98       # Probability order fills
      partial_fill_threshold: 1000 # USD threshold for partial fills
      min_fill_ratio: 0.3         # Minimum fill ratio for partials
      max_fill_time_ms: 1000      # Maximum time for fill completion

# ===== EXISTING CONFIGURATION =====
capital_allocation:
  mode: fixed_fraction
  fraction: 0.5

risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 4
  slippage_cooldown_seconds: 300
  enable_latency_checks: true
  enable_slippage_checks: true

fees:
  taker_bps: 6
  maker_bps: 1

order:
  type: market
  allow_partial_fills: false
  max_retries: 3
  retry_delay_ms: 1000
  monitoring:
    initial_delay_ms: 100
    max_delay_ms: 5000
    backoff_multiplier: 2.0

# Enhanced panic sell configuration
panic_sell:
  enabled: true
  base_currencies: ['USDC', 'USD', 'USDT']
  max_slippage_bps: 100
  use_enhanced_routing: true

simulation:
  enable: true
  book_depth_levels: 5
  latency_ms: 118

# ===== OBSERVABILITY CONFIGURATION =====
observability:
  # Prometheus metrics server
  metrics:
    enabled: true
    port: 8000
    path: /metrics

    # Custom metrics to expose
    expose:
      - cycles_started_total
      - cycles_filled_total
      - cycles_canceled_by_slippage_total
      - cycles_canceled_by_latency_total
      - average_leg_latency_seconds
      - cooldown_count
      - realized_profit_basis_points

  # Enhanced logging
  logging:
    level: INFO
    trade_csv: logs/trades_strategy_robust.csv
    risk_json: logs/risk_events_strategy_robust.json

    # Daily rolling logs for backtests
    daily_rolling: true
    max_log_files: 30

    # Structured logging for analysis
    structured_format: true
    include_metadata: true

# ===== RECONCILIATION CONFIGURATION =====
reconciliation:
  # Partial fill handling
  partial_fills:
    enabled: true
    hedge_threshold_bps: 50      # Hedge if slippage > threshold
    cancel_threshold_bps: 200    # Cancel if slippage > threshold
    max_wait_time_ms: 5000      # Max time to wait for remaining fill

  # Position tracking
  position_tracking:
    enabled: true
    tolerance_bps: 1            # Tolerance for flat position
    reconcile_on_cycle_end: true # Force reconciliation

  # Slippage-based decisions
  slippage_decisions:
    hedge_on_high_slippage: true
    cancel_on_extreme_slippage: true
    dynamic_thresholds: true     # Adjust thresholds based on volatility