name: strategy_17
exchange: coinbase
trading_pairs_file: data/cycles/coinbase_cycles_17.csv
min_profit_bps: 16
max_slippage_bps: 4
max_leg_latency_ms: 176
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 1
  stop_after_consecutive_losses: 6
fees:
  taker_bps: 7
  maker_bps: 4
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 5
  latency_ms: 118
logging:
  level: INFO
  trade_csv: logs/trades_strategy_17.csv
