name: strategy_1
exchange: binance
trading_pairs_file: data/cycles/binance_cycles_1.csv
min_profit_bps: 7
max_slippage_bps: 9
max_leg_latency_ms: 264
capital_allocation:
  mode: fixed_fraction
  fraction: 0.6
risk_controls:
  max_open_cycles: 3
  stop_after_consecutive_losses: 4
fees:
  taker_bps: 9
  maker_bps: 4
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 5
  latency_ms: 139
logging:
  level: INFO
  trade_csv: logs/trades_strategy_1.csv
