name: strategy_3
exchange: kraken
trading_pairs_file: data/cycles/kraken_cycles_3.csv
min_profit_bps: 12
max_slippage_bps: 4
max_leg_latency_ms: 311
capital_allocation:
  mode: fixed_fraction
  fraction: 0.2
risk_controls:
  max_open_cycles: 1
  stop_after_consecutive_losses: 3
fees:
  taker_bps: 5
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 9
  latency_ms: 115
logging:
  level: INFO
  trade_csv: logs/trades_strategy_3.csv
