name: strategy_6
exchange: binance
trading_pairs_file: data/cycles/binance_cycles_6.csv
min_profit_bps: 16
max_slippage_bps: 5
max_leg_latency_ms: 257
capital_allocation:
  mode: fixed_fraction
  fraction: 0.6
risk_controls:
  max_open_cycles: 1
  stop_after_consecutive_losses: 3
fees:
  taker_bps: 7
  maker_bps: 1
order:
  type: market
  allow_partial_fills: false
simulation:
  enable: true
  book_depth_levels: 10
  latency_ms: 147
logging:
  level: INFO
  trade_csv: logs/trades_strategy_6.csv
