# ===================================================================
# OPTIMIZED DEX CONFIG - Arbitrum One
#
# Multi-venue L2 arbitrage with realistic gas, liquidity, and sizing.
# Venues: Uniswap V3, Sushiswap V2, Camelot V2, Trader Joe
# ===================================================================

# ===== NETWORK & RPC =====
rpc_url: "https://arb-mainnet.g.alchemy.com/v2/YOUR_KEY_HERE"  # Replace with your Alchemy/Infura key
poll_sec: 2
once: false

# ===== TRADING PARAMETERS =====
usd_token: "USDC"
max_position_usd: 1000
price_safety_margin_pct: 0.05        # 5bp safety margin per leg
apply_safety_per_leg: false
threshold_net_pct: 0.0               # Minimum net profit (set to 0, use min_gross_bps below)

# Profit thresholding: gross profit must exceed fees + gas + slippage buffer
min_gross_bps: 60                     # 0.60% minimum gross profit on Arbitrum

# ===== GAS COST (L2 - Much cheaper!) =====
gas_price_gwei: 0.1                   # Arbitrum gas is ~0.1 gwei
gas_limit: 300000
# Estimated gas cost: 300k × 0.1 gwei × $3000/ETH ≈ $0.09
# At $1k trade size: 0.09 / 1000 = 0.9 bps
# gas_cost_usd_override: 0.10        # Override if you want fixed gas cost

# ===== TOKEN DEFINITIONS =====
tokens:
  WETH:
    address: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"  # Arbitrum WETH
    decimals: 18

  USDC:
    address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"  # Arbitrum USDC (native)
    decimals: 6

  USDT:
    address: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"  # Arbitrum USDT
    decimals: 6

  DAI:
    address: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"  # Arbitrum DAI
    decimals: 18

  WBTC:
    address: "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"  # Arbitrum WBTC
    decimals: 8

  ARB:
    address: "0x912CE59144191C1204E64559FE8253a0e49E6548"  # Arbitrum native token
    decimals: 18

# ===== DEX DEFINITIONS =====
dexes:
  # ----- Uniswap V3 -----
  - name: "uniswap_v3"
    kind: "v3"
    router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"  # SwapRouter
    quoter: "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"  # QuoterV2
    fee_tiers: [100, 500, 3000, 10000]  # 1bp, 5bp, 30bp, 100bp
    pairs:
      - name: "WETH/USDC"
        fee_bps: 5
        base: "WETH"
        quote: "USDC"
        # Note: V3 doesn't use pair addresses, uses pool per fee tier

      - name: "WETH/USDT"
        fee_bps: 5
        base: "WETH"
        quote: "USDT"

      - name: "WBTC/WETH"
        fee_bps: 5
        base: "WBTC"
        quote: "WETH"

      - name: "ARB/USDC"
        fee_bps: 5
        base: "ARB"
        quote: "USDC"

  # ----- Sushiswap V2 -----
  - name: "sushiswap"
    kind: "v2"
    router: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"
    factory: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4"
    fee_bps: 30
    pairs:
      - name: "WETH/USDC"
        address: "0x905dfCD5649217c42684f23958568e533C711Aa3"
        base: "WETH"
        quote: "USDC"

      - name: "WETH/USDT"
        address: "0xCB0E5bFa72bBb4d16AB5aA0c60601c438F04b4ad"
        base: "WETH"
        quote: "USDT"

  # ----- Camelot V2 -----
  - name: "camelot"
    kind: "v2"
    router: "0xc873fEcbd354f5A56E00E710B90EF4201db2448d"
    factory: "0x6EcCab422D763aC031210895C81787E87B43A652"
    fee_bps: 30
    pairs:
      - name: "WETH/USDC"
        address: "0x84652bb2539513BAf36e225c930Fdd8eaa63CE27"
        base: "WETH"
        quote: "USDC"

      - name: "ARB/WETH"
        address: "0xa6c5C7D189fA4eB5Af8ba34E63dCDD3a635D433f"
        base: "ARB"
        quote: "WETH"

  # ----- Trader Joe V2.1 (LB pairs) -----
  - name: "traderjoe"
    kind: "v2"
    router: "0xb4315e873dBcf96Ffd0acd8EA43f689D8c20fB30"
    factory: "0x8e42f2F4101563bF679975178e880FD87d3eFd4e"
    fee_bps: 20  # Variable, but ~20bp average
    pairs:
      - name: "WETH/USDC"
        address: "0x0000000000000000000000000000000000000000"  # Placeholder - needs actual LB pair
        base: "WETH"
        quote: "USDC"

# ===== ADAPTIVE SIZING =====
# Size trade as % of pool liquidity to minimize slippage
adaptive_sizing:
  enabled: true
  max_pct_of_liquidity: 0.05         # Trade max 5% of pool reserves
  min_liquidity_usd: 50000           # Require at least $50k liquidity per pool

# ===== SLIPPAGE & EXECUTION =====
per_leg_slippage_bps: 50             # Max 50bp per leg
cycle_slippage_bps: 100              # Max 100bp total cycle slippage

# ===== ROUTE SEARCH =====
# Define specific triangular routes (optional - or auto-discover)
# routes:
#   - base: "USDC"
#     mid: "WETH"
#     alt: "USDT"
#     # This searches USDC→WETH→USDT→USDC across all DEXes

# ===== EXECUTION MODE =====
execution_mode: "paper"              # Change to "live" for real execution

# ===== MONITORING =====
log_level: "INFO"
metrics_enabled: true
alert_on_profit: true
min_alert_profit_usd: 5

# ===== NOTES =====
# 1. Replace YOUR_KEY_HERE with actual Alchemy/Infura RPC key
# 2. For V3 pools, you'll need to query pool addresses via factory
# 3. Trader Joe V2.1 uses liquidity book pairs - addresses need lookup
# 4. Start with paper mode, validate profitability, then switch to live
# 5. Gas on Arbitrum is ~10-100x cheaper than Ethereum L1
# 6. Monitor mempool for MEV competition on high-value arbs
