# DEX/MEV Paper Trading Configuration Template
# Copy to dex_mev.yaml and customize with your values

# ===== Network Configuration =====
network: "ethereum"
chain_id: 1

# RPC configuration (environment variables)
rpc_url_env: "ETH_RPC_URL"
rpc_primary: ""  # Optional: Direct RPC URL (overrides env var)
rpc_backups: []
private_key_env: "PRIVATE_KEY"

# ===== Trading Parameters =====
# Base asset for arbitrage cycles (must be defined in tokens section)
base_asset: "USDC"

# Minimum profit threshold in basis points (after all costs)
# Paper mode: 0 to see all opportunities
# Live mode: 20+ (0.2%) recommended
min_profit_bps: 0

# Legacy slippage field (kept for compatibility, use per_leg/cycle instead)
max_slippage_bps: 50

# ===== Slippage Caps =====
# Per-leg slippage cap: Maximum slippage allowed for ANY single swap
# Example: 50 = 0.5% max per leg
per_leg_slippage_bps: 50

# Cycle slippage cap: Maximum total slippage across ALL legs
# Example: 100 = 1% max total
cycle_slippage_bps: 100

# ===== Gas Configuration =====
# Maximum base fee in gwei (abort if network gas > this)
max_base_fee_gwei: 50

# Maximum priority fee in gwei
max_priority_fee_gwei: 2

# Gas limit cap for transactions
gas_limit_cap: 500000

# ===== Private Transaction Configuration =====
# Enable private transaction submission via MEV relay (Flashbots)
private_tx_enabled: false

# MEV relay endpoint (e.g., Flashbots)
mev_relay: ""

# Simulation RPC endpoint (for pre-flight checks)
simulation_rpc: ""

# ===== Execution Options =====
# Use exactAmountIn (true) vs exactAmountOut (false)
exact_in: true

# Submit as bundle (true) vs single transaction (false)
use_bundle: false

# Legacy Flashbots fields (kept for backward compatibility)
use_flashbots: false
coinbase_tip_gwei: 0

# ===== Token Definitions =====
# Define all tokens used in your arbitrage routes
tokens:
  USDC:
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"  # Ethereum USDC
    decimals: 6

  WETH:
    address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"  # Ethereum WETH
    decimals: 18

  USDT:
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"  # Ethereum USDT
    decimals: 6

# ===== Arbitrage Routes =====
# Define the arbitrage routes to evaluate
# Format: base -> mid -> alt -> base
routes:
  - base: "USDC"
    mid: "WETH"
    alt: "USDT"
    dex_name: "UniswapV2"
    pool_addresses:
      - "0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc"  # USDC/WETH
      - "0x0d4a11d5EEaaC28EC3F61d100daF4d40471f1852"  # WETH/USDT
      - "0x3041CbD36888bECc7bbCBc0045E3B1f144466f5f"  # USDT/USDC

# ===== Notes =====
# Paper Mode Configuration:
#   - Set min_profit_bps: 0 to see all opportunities
#   - No RPC or private key needed
#   - Uses mock data for demonstration
#
# Live Mode Configuration:
#   - Set environment variables: ETH_RPC_URL, PRIVATE_KEY
#   - Set min_profit_bps: 20+ (0.2% minimum recommended)
#   - Enable private_tx_enabled: true
#   - Configure mev_relay and simulation_rpc
#
# Slippage Protection:
#   - per_leg_slippage_bps: Max slippage per individual swap
#   - cycle_slippage_bps: Max total slippage across all swaps
#   - Both must pass for route to be accepted
#
# Gas Policy:
#   - Transactions abort if gas > max_base_fee_gwei
#   - Opportunities rejected if gas cost pushes profit below min_profit_bps
