# DEX/MEV Paper Trading Configuration Template
# Copy to dex_mev.yaml and customize with your values

# ===== RPC & Scanning =====
# RPC endpoint for your target chain
# Examples:
#   - Base: https://mainnet.base.org
#   - Ethereum: https://eth.llamarpc.com
#   - Arbitrum: https://arb1.arbitrum.io/rpc
rpc_url: "https://mainnet.base.org"

# Seconds between scans
poll_sec: 6

# If true, run a single scan and exit (useful for testing/CI)
once: false

# ===== Trading Parameters =====
# Quote token symbol (must be defined in tokens section below)
# This is the token you start and end with in arbitrage cycles
usd_token: "USDC"

# Maximum position size in USD
# This is the notional amount used for each simulated trade
max_position_usd: 1000

# Slippage haircut in basis points (applied to final proceeds)
# Example: 5 = 0.05% slippage cushion
slippage_bps: 5

# Minimum net profit threshold in percentage
# Opportunities below this won't be considered for execution
# Paper mode: set to 0.0 to see all opportunities
threshold_net_pct: 0.0

# ===== Gas Cost (Informational) =====
# Gas price in Gwei (for display purposes)
gas_price_gwei: 0.5

# Gas limit estimate for a typical 2-leg arbitrage
gas_limit: 220000

# Optional: Override gas cost in USD (uncomment to use)
# If set, this will be subtracted from P&L per cycle
# Useful when gas costs are stable or you want conservative estimates
# gas_cost_usd_override: 0.05

# ===== Token Definitions =====
# Define all tokens used in your pairs
# Each token needs:
#   - address: Checksummed contract address
#   - decimals: Token decimals (18 for most, 6 for USDC/USDT)
tokens:
  WETH:
    address: "0x4200000000000000000000000000000000000006"  # Base WETH
    decimals: 18

  USDC:
    address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"  # Base USDC
    decimals: 6

  # Add more tokens as needed
  # DAI:
  #   address: "0x..."
  #   decimals: 18

# ===== DEX Definitions =====
# Define all DEXes and their pairs to monitor
# Currently only "v2" (constant-product) is supported
# Each DEX needs:
#   - name: Unique identifier
#   - kind: "v2" (v3 coming soon)
#   - fee_bps: Pool fee in basis points (30 = 0.3%)
#   - pairs: List of pool addresses to monitor
dexes:
  - name: "uniswap"
    kind: "v2"
    fee_bps: 30
    pairs:
      - name: "WETH/USDC"
        address: "0xYOUR_UNISWAP_WETH_USDC_PAIR_ADDRESS"  # REPLACE WITH ACTUAL PAIR
        base: "WETH"
        quote: "USDC"

  - name: "sushiswap"
    kind: "v2"
    fee_bps: 30
    pairs:
      - name: "WETH/USDC"
        address: "0xYOUR_SUSHI_WETH_USDC_PAIR_ADDRESS"  # REPLACE WITH ACTUAL PAIR
        base: "WETH"
        quote: "USDC"

  # Add more DEXes and pairs as needed
  # - name: "baseswap"
  #   kind: "v2"
  #   fee_bps: 25
  #   pairs:
  #     - name: "WETH/USDC"
  #       address: "0x..."
  #       base: "WETH"
  #       quote: "USDC"

# ===== Notes =====
# 1. Make sure all pair addresses are correct for your target chain
# 2. Token addresses must match what's in the pair contracts
# 3. fee_bps should match the actual pool fee (30 = 0.3% for most Uni V2 forks)
# 4. The scanner will try all combinations of pairs with matching base/quote
# 5. Depth guard: trades >10% of pool reserves are automatically rejected
# 6. This is PAPER MODE only - no transactions will be submitted
