# DEX Paper Trading Test Config - Ethereum Mainnet
# Use this to verify the scanner works before finding Base pools

# Ethereum mainnet RPC (free, rate-limited)
rpc_url: "https://eth.llamarpc.com"

poll_sec: 10
once: false  # Set to true for single scan testing

# Trading parameters
usd_token: "USDC"
max_position_usd: 1000
slippage_bps: 5
threshold_net_pct: 0.0

# Gas cost (typical Ethereum)
gas_price_gwei: 12
gas_limit: 220000
gas_cost_usd_override: 2.50  # ~$2.50 at 12 gwei + $3000 ETH

# Ethereum token addresses
tokens:
  WETH:
    address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    decimals: 18
  USDC:
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    decimals: 6

# Known working Ethereum V2 pools
dexes:
  - name: "uniswap_v2"
    kind: "v2"
    fee_bps: 30  # 0.3%
    pairs:
      - name: "USDC/WETH"
        address: "0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc"  # Verified working
        base: "WETH"
        quote: "USDC"

  - name: "sushiswap"
    kind: "v2"
    fee_bps: 30  # 0.3%
    pairs:
      - name: "USDC/WETH"
        address: "0x397FF1542f962076d0BFE58eA045FfA2d347ACa0"  # Verified working
        base: "WETH"
        quote: "USDC"

# Note: These are real Ethereum mainnet pools verified with scripts/check_pair.py
# Gas costs are much higher on Ethereum (~$2.50) vs Base (~$0.01)
# So arbitrage opportunities need to be larger to be profitable
