# DEX MEV Arbitrage Configuration
# This is an example configuration - copy and modify for your needs

# Chain configuration
chain_id: 1  # Ethereum mainnet
rpc_url_env: "ETH_RPC_URL"  # Environment variable containing RPC URL
private_key_env: "PRIVATE_KEY"  # Environment variable containing private key

# Base asset for arbitrage calculations
base_asset: "USDC"

# Profitability thresholds
min_profit_bps: 10  # Minimum profit in basis points (0.1%)
max_slippage_bps: 10  # Maximum slippage allowance (0.1%)

# Gas configuration
max_gas_gwei: 30  # Maximum gas price in gwei
coinbase_tip_gwei: 2  # MEV tip for Coinbase builders

# MEV configuration
use_flashbots: true  # Use Flashbots for MEV protection

# Arbitrage routes (base -> mid -> alt -> base cycles)
routes:
  - base: "USDC"
    mid: "WETH"
    alt: "USDT"
    dex_name: "Uniswap V3"
    pool_addresses:
      - "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"  # USDC/WETH
      - "0x11b815efB8f581194ae79006d24E0d814B7697F6"  # WETH/USDT
      - "0x3416cF6C708Da44DB2624D63ea0AAef7113527C6"  # USDT/USDC

  - base: "USDC"
    mid: "WBTC"
    alt: "DAI"
    dex_name: "Uniswap V3"
    pool_addresses:
      - "0x99ac8cA7087fA4A2A1FB6357269965A2014ABc35"  # USDC/WBTC
      - "0x6Ce8dA28E2f864420840cF74474eFf5fD80E65B8"  # WBTC/DAI
      - "0x6c6Bc977E13Df9b0de53b251522280BB72383700"  # DAI/USDC

  - base: "USDC"
    mid: "UNI"
    alt: "LINK"
    dex_name: "Uniswap V3"
    pool_addresses:
      - "0xd0fc8bA7E267f2bc56044A7715A489d851dC6D78"  # USDC/UNI
      - "0x1d42064Fc4Beb5F8aAF85F4617AE8b3b5B8Bd801"  # UNI/LINK
      - "0xfAd57d2039C21811C8F2B5D5B65308aa99D31559"  # LINK/USDC

# Token configurations
tokens:
  USDC:
    address: "0xA0b86a33E6417A4b4c0CbC383c5Ef3B0CcC7C9b0"
    decimals: 6
  WETH:
    address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    decimals: 18
  USDT:
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    decimals: 6
  WBTC:
    address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
    decimals: 8
  DAI:
    address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    decimals: 18
  UNI:
    address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"
    decimals: 18
  LINK:
    address: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
    decimals: 18

# Required environment variables:
# - ETH_RPC_URL: Ethereum RPC endpoint URL (e.g., Alchemy, Infura)
# - PRIVATE_KEY: Private key for wallet (0x prefixed hex string)
#
# Example:
# export ETH_RPC_URL="https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY"
# export PRIVATE_KEY="0x1234567890abcdef..."
