# DEX Paper Trading Config - BSC (Best for Finding Inefficient Routes)
# BSC has many copycat tokens, shallow liquidity, and frequent mispricings

# BSC mainnet RPC (free, public)
rpc_url: "https://bsc-dataseed.binance.org"

poll_sec: 3  # Scan every 3 seconds - leverage 5s cache for speed
once: false

# Trading parameters
usd_token: "USDT"  # USDT is more common on BSC than USDC
max_position_usd: 500  # Smaller size due to lower liquidity
slippage_bps: 20  # Higher slippage tolerance for thin pools
threshold_net_pct: 0.0  # Show all opportunities

# Gas cost (BSC uses BNB for gas, very cheap)
gas_price_gwei: 3.0  # ~3 gwei on BSC
gas_limit: 200000
gas_cost_usd_override: 0.15  # ~$0.15 per trade (BNB at ~$500)

# Tokens for BSC
tokens:
  USDT:
    address: "0x55d398326f99059fF775485246999027B3197955"  # BSC USDT
    decimals: 18
  WBNB:
    address: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"  # Wrapped BNB
    decimals: 18
  BUSD:
    address: "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"  # Binance USD
    decimals: 18
  USDC:
    address: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"  # BSC USDC
    decimals: 18

# Dynamic pool discovery - AGGRESSIVE discovery for maximum opportunities
dynamic_pools:
  enabled: true
  use_smart_discovery: true  # Use smart discovery (prioritizes cross-DEX pairs)
  min_liquidity_usd: 3000    # Target thin pools with wide spreads (was 5000)
  max_pools_per_dex: 350     # Discover MANY pools per DEX (was 100)
  max_scan_pools: 2000       # DEEP scan - find hidden opportunities (was 1000)

  # Factory contracts on BSC
  factories:
    - name: "pancakeswap_v2"
      address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"  # PancakeSwap V2 Factory
      fee_bps: 25  # 0.25% fee

    - name: "biswap"
      address: "0x858E3312ed3A876947EA49d572A7C42DE08af7EE"  # Biswap Factory
      fee_bps: 10  # 0.10% fee (very low!)

    - name: "apeswap"
      address: "0x0841BD0B734E4F5853f0dD8d7Ea041c241fb0Da6"  # ApeSwap Factory
      fee_bps: 20  # 0.20% fee

# Legacy static pools (disabled)
dexes: []

# Why BSC is Excellent for Finding Opportunities:
# 1. Many thin, inefficient pools with high spreads (+0.5% to +2.0% common)
# 2. Low fees on some DEXes (Biswap at 0.10%)
# 3. Copycat tokens create temporary arbitrage windows
# 4. Less sophisticated MEV infrastructure than Ethereum
# 5. Lower gas costs allow profiting from smaller edges
# 6. Expected gross profits: +0.5% to +1.5% before costs
